.\" Author: Jose Luis Tallon <jltallon@adv-solutions.net>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with the Debian GNU/Linux system; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307 USA
.TH basket "23" "October 2004"
.SH NAME
basket \- user-friendly way to run programs and manage links in KDE.
.SH SYNOPSIS
basket
.SH DESCRIPTION
.B basket
is an user-friendly way to run programs and manage links in KDE.
.PP
This application provides as many baskets (drawers) as you wish;
Several kinds of objects (texts, URLs, images,...) can be 
drag-n-drop'd into it.
.PP
Objects can be edited, copied, dragged... So, they can be arranged
according to users' taste. Moreover, Basket allows you to keep all 
objects you want in one place, keep data on hand, take notes...
.PP
Complete documentation can be found in docbook format in
/usr/share/doc/kde/HTML/<lang>/basket/ on this system.
.SH AUTHOR
Sebastien Laout <sebastien.laout@tuxfamily.org>
.PP
This manual page was written by Jose Luis Tallon 
.nh
<jltallon@adv\-solutions.net> 
for the \fBDebian\fP system (but may be used by others).
